export const map = {
  allTasks: {
    title: "Все задачи",
    count: 0,
    icon: "allRequestIcon.svg",
    link: "",
    priority: 1,
  },
  newTasks: {
    title: "Новые",
    count: 0,
    icon: "newRequestIcon.svg",
    link: "new",
    priority: 2,
  },
  today: {
    title: "Сегодня",
    count: 0,
    icon: "todayRequestIcon.svg",
    link: "today",
    priority: 4,
  },
  expired: {
    title: "Просроченные",
    count: 0,
    icon: "overdueRequestIcon.svg",
    link: "expired",
    priority: 3,
  },
  allAccepted: {
    title: "В работе",
    count: 0,
    icon: "InWorkRequestionIcon.svg",
    link: "accepted",
    priority: 5,
  },
  allNonAccepted: {
    title: "В ожидании",
    count: 0,
    icon: "waitingRequestIcon.svg",
    link: "nonaccepted",
    priority: 6,
  },
  parent: {
    title: "Поручение от головной орг-ии",
    count: 0,
    icon: "OutExecutor.svg",
    link: "nonaccepted",
    priority: 6,
  },
};
